# Generated by Django 5.2.5 on 2025-09-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_clients/')),
            ],
        ),
    ]
