# Generated by Django 5.2.5 on 2025-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_our_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/')),
            ],
        ),
    ]
